site_name: Python and data science
theme:
  # appearance
  name: material
  features:
    - navigation.instant
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  # note boxes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # highlight code syntax
  - pymdownx.highlight:
        anchor_linenums: true
  # footnotes
  - footnotes
  # for mathjax
  - pymdownx.arithmatex:
        generic: true
  # support for image alignment, etc.
  - md_in_html
  # permalinks to page sections
  - toc:
      permalink: true
  # icons + emojis
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
# for mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# table of contents
nav:
  - 'index.md'
  - 'Python':
    - 'programming/python/python_introduction.md'
    - 'programming/python/control_flow.md'
    - 'programming/python/data_structures.md'
    - 'programming/python/functions.md'
    - 'programming/python/python_programs.md'
    - 'programming/python/io_exceptions.md'
    - 'programming/python/classes.md'
    - 'programming/python/python_packages.md'
  - 'Data libraries':
    - 'programming/python_libraries/pandas.md'
    - 'programming/python_libraries/numpy.md'
    - 'programming/python_libraries/matplotlib.md'
#    - 'programming/pyspark.md'
  - 'SQL':
    - 'programming/sql.md'
