site_name: Python and data science
theme:
  # appearance
  name: material
  features:
    - navigation.instant
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - attr_list
  # note boxes
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # highlight code syntax
  - pymdownx.highlight:
        anchor_linenums: true
  # footnotes
  - footnotes
  # for mathjax
  - pymdownx.arithmatex:
        generic: true
  # support for image alignment, etc.
  - md_in_html
  # permalinks to page sections
  - toc:
      permalink: true
  # icons + emojis
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
# for mathjax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

# table of contents
nav:
  - index.md
  - Python 1:
    - sections/python/python_introduction.md
    - sections/python/control_flow.md
    - sections/python/data_structures.md
    - sections/python/functions.md
    - sections/python/python_programs.md
    - sections/python/io_files.md
    - sections/python/exceptions.md
    - sections/python/classes.md
  - Python 2:
    - sections/python/datetime.md
    - sections/python/regular_expressions.md
    - sections/python_libraries/sqlalchemy.md
    - sections/python/python_projects.md
    - sections/other/git.md
    - Scikit Learn:
      - sections/python_libraries/sklearn/sklearn_introduction.md
      - sections/python_libraries/sklearn/sklearn_estimators.md
      - sections/python_libraries/sklearn/sklearn_models_metrics.md
      - sections/python_libraries/sklearn/sklearn_features.md
      - sections/python_libraries/sklearn/sklearn_time_series.md
      - sections/python_libraries/sklearn/sklearn_annex.md
    - sections/python_libraries/typer.md
    - sections/python_libraries/streamlit.md
  - Other Python topics:
#    - sections/python/builtin_functions.md
#    - sections/python/dataclasses.md
#    - sections/python/decorators.md
#    - sections/python/generators.md
    - sections/python/comprehensions.md
    - sections/python/decorators.md
    - sections/other/web_scraping.md

  - Python data libraries:
    - sections/python_libraries/numpy.md
    - sections/python_libraries/matplotlib.md
    - sections/python_libraries/pandas.md
    - sections/python_libraries/pyspark.md
  - SQL:
    - sections/sql/introduction.md
    - sections/sql/select_statements.md
    - sections/sql/window_functions.md
    - sections/sql/modification_statements.md
    - sections/sql/table_operations.md
    - sections/sql/sql_from_python.md